### ISSUE TITLE
'Cured'

### ISSUE THREAD

**Issue by nv0id** [takitsu21/covid-19-tracker#8]
## ISSUE
Use of the work 'cured' is incorrect as there is no cure for COVID-19 (currently)
## HOW TO REPRODUCE ISSUE
Using the command 

``` c!country united kingdom ```

 produces:

```Country affected by COVID-19
You can support me on :kofi:Kofi and vote on top.gg for the bot. :github: Source code
:confirmed: Confirmed 1493162 [+-20139]
:recov: Recovered 303892 (20.35%) [+2794]
:_death: Deaths 88996 (5.96%) [+646]

United Kingdom : 61459 :confirmed: [+13], 350 cured [+6], 7110 deaths [+0]
United States : 432427 :confirmed: [+3386], 0 cured [+0], 14806 deaths [+113]
United States M... : 0 :confirmed: [+0], 0 cured [+0], 0 deaths [+0]
United Arab Emi... : 2659 :confirmed: [+0], 239 cured [+0], 12 deaths [+0] 
```

## PROPOSED SOLUTION
Change 'cured' to 'recovered'

Great bot btw! Keep up the good work

-nvoid

**Comment by takitsu21** [comment]
Okay thank you for reporting this issue, I'll consider this solution in the next update :)

**Comment by takitsu21** [comment]
Considering this issue fixed.
